version: "3.0"
services:

  web:
    image: nginx:latest
    container_name: web-server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/letsencrypt:/etc/letsencrypt
      - ./www:/srv/blog/www

  node:
    image: node:prod
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node-server
    restart: on-failure
    working_dir: /srv/blog
    volumes:
      - ./mynote:/srv/blog/mynote
    command: ["node", "production.js"]

  db:
    image: mysql:8.0
    container_name: mysql-server
    restart: on-failure
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=abc123_