version: "3.0"
services:

  web:
    image: nginx:dev
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: web-server
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf

  node:
    image: node:dev
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node-server
    restart: on-failure
    working_dir: /srv/blog
    volumes:
      - ./mynote:/srv/blog/mynote
    command: ["node", "development.js"]

  db:
    image: mysql:8.0
    container_name: mysql-server
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=abc123_